name: Deploy Dummy React App
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Client
        run: docker build -t brownninja1994/dummy-react-app -f Dockerfile.dev .
      - name: Run Unit Tests
        run: docker run -e CI=true brownninja1994/dummy-react-app npm run test
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: dummy-react-app-ci
          environment_name: Dummy-react-app-ci-env
          existing_bucket_name: elasticbeanstalk-eu-west-2-501244959312
          region: eu-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip